apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konfd
  namespace: kube-system
spec:
  replicas: 1
  strategy:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: template-engine
        component: konfd
    spec:
      containers:
        - name: konfd
          image: "hbouvier/konfd:v0.0.4-001"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 50m
              memory: 128Mi
        - name: kubectl
          image: "gcr.io/google_containers/hyperkube:v1.4.6"
          command:
            - "/hyperkube"
          args:
            - "kubectl"
            - "proxy"
