apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: node-red
    component: couchdb
spec:
  ports:
  - name: http
    port: 5984
  selector:
    app: node-red
    component: couchdb
